name       : fzf
version    : 0.19.0
release    : 8
source     :
    - https://github.com/junegunn/fzf/archive/0.19.0.tar.gz : 4d7ee0b621287e64ed450d187e5022d906aa378c5390d8c7c1f843417d2f3422
license    : MIT
component  : system.utils
summary    : fzf is a general-purpose command-line fuzzy finder
description: |
    fzf is a general-purpose command-line fuzzy finder
networking : yes
builddeps  :
    - golang
    - git
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-include-external-ldflags.-It-doesn-t-like-them.patch
build      : |
    %make
install    : |
    %make_install
    install -Dm00755 bin/fzf $installdir/usr/bin/fzf
    install -Dm00755 bin/fzf-tmux $installdir/usr/bin/fzf-tmux
    install -Dm00644 man/man1/fzf.1 $installdir/usr/share/man/man1/fzf.1
    install -Dm00644 man/man1/fzf-tmux.1 $installdir/usr/share/man/man1/fzf-tmux.1
    install -Dm00644 shell/completion.bash $installdir/usr/share/bash-completion/completions/fzf
    install -Dm00644 shell/completion.zsh $installdir/usr/share/zsh/site-functions/_fzf
    install -Dm00644 plugin/fzf.vim $installdir/usr/share/vim/vimfiles/plugin/fzf.vim
    install -dm00755 $installdir/usr/share/fzf
    install -Dm00644 shell/key-bindings.* $installdir/usr/share/fzf
