name       : fzf
version    : 0.17.5
release    : 5
source     :
    - https://github.com/junegunn/fzf/archive/0.17.5.tar.gz : de3b39758e01b19bbc04ee0d5107e14052d3a32ce8f40d4a63d0ed311394f7ee
license    : MIT
component  : system.utils
summary    : fzf is a general-purpose command-line fuzzy finder
description: |
    fzf is a general-purpose command-line fuzzy finder
networking : yes
builddeps  :
    - golang
    - git
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-include-external-ldflags.-It-doesn-t-like-them.patch
build      : |
    %make
install    : |
    %make_install
    install -D -m 00755 bin/fzf $installdir/usr/bin/fzf
    install -D -m 00755 bin/fzf-tmux $installdir/usr/bin/fzf-tmux
    install -D -m 00644 man/man1/fzf.1 $installdir/usr/share/man/man1/fzf.1
    install -D -m 00644 man/man1/fzf-tmux.1 $installdir/usr/share/man/man1/fzf-tmux.1
    install -D -m 00644 shell/completion.bash $installdir/usr/share/bash-completion/completions/fzf
