name       : fzf
version    : 0.16.7
release    : 2
source     :
    - https://github.com/junegunn/fzf/archive/0.16.7.tar.gz : 9676664e02393d19dd0f0a1ae4cf5d20e3fffcba666a0cffc40ff6c590c67760
license    : MIT
component  : system.utils
summary    : fzf is a general-purpose command-line fuzzy finder
description: |
    fzf is a general-purpose command-line fuzzy finder
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    sed -i 's/-ldflags "-w -extldflags=$(LDFLAGS)"/-ldflags -w/g' src/Makefile
build      : |
    cd src
    %make
install    : |
    pushd src
    %make_install
    popd
    install -D -m 00755 bin/fzf $installdir/usr/bin/fzf
    install -D -m 00755 bin/fzf-tmux $installdir/usr/bin/fzf-tmux
    install -D -m 00644 man/man1/fzf.1 $installdir/usr/share/man/man1/fzf.1
    install -D -m 00644 man/man1/fzf-tmux.1 $installdir/usr/share/man/man1/fzf-tmux.1
    install -D -m 00644 shell/completion.bash $installdir/usr/share/bash-completion/completions/fzf
