name       : fzf
version    : 0.15.8
release    : 1
source     :
    - https://github.com/junegunn/fzf/archive/0.15.8.tar.gz : f02ba45837e8583a3aa4e54a7d0b7d493f5314be6923ca80a639b43d6c0f4a4f
license    : MIT
component  : system.utils
summary    : fzf is a general-purpose command-line fuzzy finder
description: |
    fzf is a general-purpose command-line fuzzy finder
networking : yes
builddeps  :
    - git
    - golang
build      : |
    cd src
    %make
install    : |
    pushd src
    %make_install
    popd
    install -D -m 00755 bin/fzf $installdir/usr/bin/fzf
    install -D -m 00755 bin/fzf-tmux $installdir/usr/bin/fzf-tmux
    install -D -m 00644 man/man1/fzf.1 $installdir/usr/share/man/man1/fzf.1
    install -D -m 00644 man/man1/fzf-tmux.1 $installdir/usr/share/man/man1/fzf-tmux.1
    install -D -m 00644 shell/completion.bash $installdir/usr/share/bash-completion/completions/fzf
