name       : fzf
version    : 0.17.1
release    : 3
source     :
    - git|https://github.com/junegunn/fzf.git : 0.17.1
license    : MIT
component  : system.utils
summary    : fzf is a general-purpose command-line fuzzy finder
description: |
    fzf is a general-purpose command-line fuzzy finder
networking : yes
builddeps  :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-include-external-ldflags.-It-doesn-t-like-them.patch
build      : |
    %make
install    : |
    %make_install
    install -D -m 00755 bin/fzf $installdir/usr/bin/fzf
    install -D -m 00755 bin/fzf-tmux $installdir/usr/bin/fzf-tmux
    install -D -m 00644 man/man1/fzf.1 $installdir/usr/share/man/man1/fzf.1
    install -D -m 00644 man/man1/fzf-tmux.1 $installdir/usr/share/man/man1/fzf-tmux.1
    install -D -m 00644 shell/completion.bash $installdir/usr/share/bash-completion/completions/fzf
